### ISSUE TITLE
Schedule information always in English

### ISSUE THREAD

**Issue by GattoJohnny** [balassy/MMM-Futar#10]
Hi @balassy,

Schedule information is shown in English regardless of the language setting in the config file.
![MMM-Futar_20190818-01](https://user-images.githubusercontent.com/47010649/63227904-00b7d100-c1ec-11e9-881f-f649b015c85d.jpg)

The language parameter does affect the initial "Loading" text, e.g. "Chargement" for french, "Lade" for german, "Loading" for english and "Menetrend betöltése" for hungarian, but time information are always displayed in english.

Raspberry Pi 3 Model B+, Raspbian Buster, kernel 4.19, MM 2.8.0, MMM-Futar v1.5.1. 

Config attached.
[config_js_20190818-01.txt](https://github.com/balassy/MMM-Futar/files/3513350/config_js_20190818-01.txt)

Cheers, Gyuri

**Comment by balassy** [comment]
Hello @GattoJohnny,

Thanks for reporting this issue. I can confirm that this is a bug in the MMM-Futar module 1.5.1 version that arise only if there are no other module on the screen that would explicitly set the locale (e.g. the calendar-monthly module).

I fixed this bug in the latest [1.5.2](https://github.com/balassy/MMM-Futar/releases/tag/1.5.2) version. Could you please update to the latest version and report back whether the bug is fixed now?

Thank you!

**Comment by GattoJohnny** [comment]
![MMM-Futar_20190819-01](https://user-images.githubusercontent.com/47010649/63251163-744df280-c26d-11e9-81da-9eb028911cf3.jpg)

Bug fixed. Thank you.
Live long and prosper.

**Comment by balassy** [comment]
Excellent, thank you!
